### PR TITLE
Allow specifying columns

### PR DESCRIPTION
**Pull request by northeastprince**

### CODE REVIEW

**Comment by ankane** [comment]
Hi @northeastprince, thanks for the PR, but I don't see `columns` in the [Vega spec](https://vega.github.io/vega/docs/specification/).

**Comment by northeastprince** [comment]
https://vega.github.io/vega-lite/docs/concat.html#:~:text=the%20%22columns%22%20property

**Comment by ankane** [comment]
It looks like that's part of Vega Lite (rather than Vega, which is what the PR changes).

**Comment by northeastprince** [comment]
Fixed

**Comment by ankane** [comment]
From the Vega Lite link, it looks like you can also do:

```ruby
config(concat: {columns: 2})
```

so I'm not sure an additional method is needed.

**Comment by northeastprince** [comment]
Unfortunately not, because `columns` is a top-level property like `concat`.

**Pull request closed without merging**
