### PR TITLE
Add optional nonce to vega embed script tag

### PR DESCRIPTION
**Pull request by dorianmariefr**

### CODE REVIEW

**Comment by dorianmariefr** [comment]
@ankane any chance this can get merged?

**Comment by ankane** [comment]
Hey @dorianmariefr, thanks for the PR! Let's escape the nonce with `ERB::Util.html_escape` to prevent injection.

**Comment by dorianmariefr** [comment]
@ankane thanks, good idea, done

**Comment by ankane** [comment]
Great, thanks @dorianmariefr!

**Comment by ankane** [comment]
Also added a `vega_chart` helper that'll add it automatically when Rails is configured to add it. 9c7b47b13ac2c13734b75d275d062129381f1f99

**Comment by dorianmariefr** [comment]
nice, thanks

**Pull request merged**
